[package]
name = "sjgfx-vulkano"
edition = "2021"
version = "0.1.0"

[dependencies]
bytemuck.workspace = true
sjvi = { path = "../vi-rs" }
sjgfx-interface = { path = "../gfx-interface" }
vulkano = "0.33.0"
vulkano-win = "0.33.0"
winit.workspace = true
raw-window-handle.workspace = true

[dev-dependencies]
sjgfx-util = { path = "../gfx-util" }
