[workspace]
resolver = "2"
members = [
    "sj",
	"examples/hello_graphics_pipeline",
	"examples/hello_3d",
	"examples/hello_compute",
	"examples/hello_draw_indexed",
	"examples/mandelbrot",
	"examples/shader_setup",
	"examples/simple_window",
]
