[workspace]
members = [
    "sj",
	"examples/hello_gfx",
	"examples/hello_graphics_pipeline",
	"examples/hello_3d",
	"examples/hello_compute",
	"examples/mandelbrot",
	"examples/shader_setup",
	"examples/simple_window",
]