[package]
name = "sjgfx-util"
edition = "2021"
version = "0.1.0"

[dependencies]
sjgfx-interface = { path = "../gfx-interface" }
tobj = "3.2.1"
naga = { version = "0.10.0", features = ["glsl-in", "spv-out", "wgsl-out"] }
rspirv = "0.7.0"