[package]
name = "sjgfx-glow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sjgfx-interface = { path = "../gfx-interface" }
glow = "*"
glutin = "*"
winit = "0.26.0"
raw-window-handle = "0.4.0"