[package]
name = "sjgfx-glow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sjgfx-interface = { path = "../gfx-interface" }
sjvi = { git = "https://github.com/dearshuto/vi-rs.git", branch = "develop" }
glow = "*"
winit = "0.26.0"
glutin = "*"
raw-window-handle = "0.4.0"
lazy_static = "1.4.0"
uuid = { version = "0.8.0", features = ["v4"] }

[dev-dependencies]