[package]
name = "sj"
edition = "2018"
version = "0.21.0"

[features]
default = ["backend_vulkano"]
backend_vulkano = ["vulkano", "vulkano-win"]
backend_wgpu = ["wgpu"]

[dependencies]
winit = "0.24.0"
vulkano =  {version = "*", optional = true}
vulkano-win = {version = "*", optional = true}
wgpu = {version = "*", optional = true}
futures = "0.3.1"