[package]
name = "sjgfx"
edition = "2021"
version = "0.1.0"

[dependencies]
sjvi = { path = "../vi-rs" }
sjgfx-interface = { path = "../gfx-interface" }
sjgfx-wgpu = { path = "../gfx-wgpu" }
sjgfx-vulkano = { path = "../gfx-vulkano" }
winit.workspace = true
raw-window-handle.workspace = true

[dev-dependencies]
shaderc.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
# nalgebra-glm = "0.3"

[features]
default = ["backend-wgpu"]
backend-ash = []
backend-wgpu = []
