[package]
name = "sjwgpu-wgpu"
edition = "2021"
version = "0.1.0"

[dependencies]
sjgfx-interface = { path = "../gfx-interface" }
wgpu = {version = "0.12.0", features = ["spirv"]}
futures = "0.3.1"
raw-window-handle = "0.4"
spirv-reflect = "0.2.3"

[dev-dependencies]
shaderc = "0.7"
winit = "0.26.0"