[package]
name = "sjgfx-wgpu"
edition = "2021"
version = "0.1.0"

[dependencies]
sjvi = { path = "../vi-rs" }
sjgfx-interface = { path = "../gfx-interface" }
sjgfx-util = { path = "../gfx-util" }
futures = "0.3.1"
raw-window-handle = "0.4.0"
rspirv = "0.11.0"
spirv = "0.2.0"
winit = "0.26.0"
web-sys = { version = "0.3.60", features = [
    "Location",
    "Blob",
    "RequestInit",
    "RequestMode",
    "Request",
    "Response"
] }
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"
wasm-bindgen-futures = "0.4.33"
parking_lot = ">=0.11,<0.13"
bytemuck = { version = "*", features = ["derive"] }
uuid = { version = "1.2.1", features = ["v4", "js"] }
futures-intrusive = "0.4"
naga = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = {version = "0.13.0", features = ["spirv"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = {version = "0.13.0", features = ["webgl", "spirv", "glsl"]}

[dev-dependencies]
sjgfx-util = { path = "../gfx-util" }
winit = "0.26.0"
nalgebra-glm = "0.3"
image = "0.24.0"
# shaderc = "0.7"