[package]
name = "sjgfx-wgpu"
edition = "2021"
version = "0.1.0"

[dependencies]
sjgfx-interface = { path = "../gfx-interface" }
wgpu = {version = "0.12.0", features = ["spirv"]}
futures = "0.3.1"
raw-window-handle = "0.4.0"
spirv-reflect = "0.2.3"
winit = "0.26.0"
egui = "*"
epi = "*"
egui_winit_platform = "0.13.0"
egui_wgpu_backend = "0.16.0"
egui_demo_lib = "0.16" # TODO

[dev-dependencies]
shaderc = "0.7"
winit = "0.26.0"
nalgebra-glm = "0.3"
image = "0.24.0"