[package]
name = "sjgfx-wgpu"
edition = "2021"
version = "0.1.0"

[dependencies]
sjvi = { path = "../vi-rs" }
sjgfx-interface = { path = "../gfx-interface" }
sjgfx-util = { path = "../gfx-util" }
futures.workspace = true
raw-window-handle.workspace = true
winit.workspace = true
bytemuck.workspace = true
uuid.workspace = true
futures-intrusive = "0.5.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "0.17.0", features = ["spirv"] }
spirv-reflect = "0.2.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.17.0", features = ["spirv", "webgl"] }

[dev-dependencies]
sjgfx-util = { path = "../gfx-util" }
winit.workspace = true
nalgebra-glm.workspace = true
image.workspace = true
wasm-bindgen.workspace = true
bytemuck.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
web-sys = { version = "0.3.61", features = [
    "Location",
    "Blob",
    "RequestInit",
    "RequestMode",
    "Request",
    "Response",
] }
